# Site settings
title: Lin Gao
email: lgao.lynne@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   Ph.D. student from the University of Waterloo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lynnegao.me/" # the base hostname & protocol for your site
production_url: "http://lynnegao.me/"
github_username: lynnegaogao
permalink: /blog/:year/:month/:title.html

twitter:
  username: lynnegaogao

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
